### ISSUE TITLE
Change default value of global.ingress.certManager.issuerName to 'letsencrypt-production'

### ISSUE THREAD

**Issue by sindram** [tum-gis/sddi-ckan-k8s#27]
### Feature description

The current default value for certManager.issuerName is set to 'letsencrypt-staging'. Staging certs are not valid in common browsers. Please change to 'letsencrypt-production'

**Comment by BWibo** [comment]
There is a specific reason, why we set staging certificates as default. Let's Encrypt has a relatively strict rate limit (see [here](https://letsencrypt.org/docs/rate-limits/)) for certificate issuance. To avoid ending up on the block list, the usual workflow should be to use stating certificates in the first place, and then switch to production, when things are stable.

Staging certificates are by definition *not valid*. But I think it's not a big deal to allow the exception for testing.

**Comment by BWibo** [comment]
@sindram For sake of completeness: 
If you want a client (e.g. a Browser) to trust the Let's Encrypt staging environment, you can add the [root certificates](https://letsencrypt.org/docs/staging-environment/#root-certificates) to the trusted CA's too.
