### ISSUE TITLE
Option to replace background/header image

### ISSUE THREAD

**Issue by ilhanDKSR** [tum-gis/sddi-ckan-k8s#3]
### Feature description

Is there an easy way to replace the background/header image? And, if not, it would be great to have one.

**Comment by BWibo** [comment]
Yes, this needs to be resolved in the Docker image. This and some other styling related issues are already being worked on:

- [ ] tum-gis/ckan-docker#23

**Comment by MarijaKnezevic** [comment]
The [ckan-docker v 1.1.0](https://github.com/tum-gis/ckan-docker/releases/tag/1.1.0) includes improvements which are mentioned in issue tum-gis/ckan-docker#23

**Comment by BWibo** [comment]
Re-opening, as this is not fully resolved. The new docker image supports this now, but the options are not jet documented and mapped to the Helm chart.

**Comment by ilhanDKSR** [comment]
Hi, and thanks for the quick feedback. From what I can tell, the current solution is to do this before deployment but after building the image, right? Is there also an option to do this on a running instance?

**Comment by MarijaKnezevic** [comment]
@ilhanDKSR You can do this either before deployment or in a running instance.
The latest image includes the option to change this in the running instance. See the [cangelog](https://github.com/tum-gis/ckan-docker/blob/1.1.0/CHANGELOG.md) to see which options are added.
In the running instance, you can change this only if you are Admin. You should select "Systemadmin settings" -->"Config" Button, as shown in the following image. There you can add/remove/change text and images.
![image](https://github.com/tum-gis/sddi-ckan-k8s/assets/93824048/ac42762f-6473-413b-a8f9-2b4fac2acf96)

**Comment by BWibo** [comment]
@MarijaKnezevic Thx, for the quick replay. What's the status on the documentation of these new options?

With the stack you can currently do it both ways with a little tewak. Using the [`ckan.extraEnv`](https://github.com/tum-gis/sddi-ckan-k8s/tree/main/charts/sddi-ckan/charts/ckan#values) the required variables can be passed using the helm chart already, to supply the options at deploy time. However, I am going to expose them in the ckan values as soon as there is a proper documentation, see #8.

**Comment by MarijaKnezevic** [comment]
@BWibo for status with documentation please see the following issue:
- [ ] https://github.com/tum-gis/ckanext-grouphierarchy-sddi/issues/12
It is on my to-do list for today and tomorrow

**Comment by BWibo** [comment]
Resolved in `v1.1.1`
